codecov:
  require_ci_to_pass: no
coverage:
  status:
    project:
      default:
        target: 90%
  notify:
    slack:
      default:
        url: "secret:Pf4awvfjSFRWbTbH3UZoQulNocK1YtmoWHz4ABT4KK51/1OEwjtAQKQWa/AZMVQ8NcuOrDkQdAFKgJ38HagRPVa+5Atw79COHgAuEfYdivBeVARPgQT9do2PWuvx1ViWqtJFWGJtIBg4EdsoYqYZmwrHKJWEszXNWVY55bsZo2Q="
